services:
  product-service:
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - discovery-server
      - api-gateway