services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
#    Run with: docker-compose -f docker-compose-keycloak.yml up
    command: ["start-dev", "--import-realm"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realm/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql