server:
  port: 8082

spring:
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spring-boot-microservices-realm
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint:  http://zipkin:9411/api/v2/spans