server:
  #random port, Allows inventory-service to be started on a random port
  port: 0

spring:
  application:
    name: inventory-service
  datasource:
    # The correct, modern driver class name for MySQL 8+
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/order-service
    username: root
    password: mysql
  jpa:
    hibernate:
      # Don't use drop in production - it deletes all data
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
       endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"